#!/system/bin/sh
# Magisk Module Installer Script
# Generated by Camera Port Studio

SKIPUNZIP=1
MODDIR=${0%/*}

ui_print "****************************************"
ui_print "  MIUI / HyperOS Camera Port Module"
ui_print "  Device: {{DEVICE_NAME}} ({{CODENAME}})"
ui_print "****************************************"

# Extract module files
ui_print "- Extracting module files..."
unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2

# Set permissions
ui_print "- Setting permissions..."
set_perm_recursive $MODPATH 0 0 0755 0644
set_perm_recursive $MODPATH/system/priv-app 0 0 0755 0644
set_perm $MODPATH/system/priv-app/MiuiCamera/MiuiCamera.apk 0 0 0644
set_perm $MODPATH/system/etc/device_features 0 0 0755
set_perm $MODPATH/system/etc/device_features/{{CODENAME}}.xml 0 0 0644

# Grant priv-app permissions if present
if [ -f $MODPATH/system/etc/permissions/privapp-permissions-miuicamera.xml ]; then
  set_perm $MODPATH/system/etc/permissions/privapp-permissions-miuicamera.xml 0 0 0644
fi

# Disable stock camera if needed (optional)
{{DISABLE_STOCK_CAMERA}}

ui_print "- Installation complete!"
ui_print "  Reboot recommended."
ui_print "****************************************"
