#!/system/bin/sh
# post-fs-data.sh - Early boot stage
# Generated by Camera Port Studio for {{DEVICE_NAME}}

MODDIR=${0%/*}

# Reset props early for camera spoof / HyperOS compatibility
{{RESETPROP_BLOCK}}

# Bind-mount device_features if needed (Android 15+/16 sandbox)
if [ -d /system/etc/device_features ]; then
  mkdir -p $MODDIR/system/etc/device_features
  # Prefer our generated XML
  if [ -f $MODDIR/system/etc/device_features/{{CODENAME}}.xml ]; then
    mount -o bind $MODDIR/system/etc/device_features/{{CODENAME}}.xml /system/etc/device_features/{{CODENAME}}.xml 2>/dev/null
  fi
fi

# Library fix for system_ext on Android 16
{{LIBRARY_FIX_BLOCK}}

# SELinux permissive rules via magiskpolicy (if available)
{{SELINUX_BLOCK}}
