#!/system/bin/sh
# service.sh - Late start service
# Generated by Camera Port Studio

MODDIR=${0%/*}

# Wait for boot completed
while [ "$(getprop sys.boot_completed)" != "1" ]; do
  sleep 1
done

# Soft thermal profile for 8K / long recording (optional)
{{THERMAL_BLOCK}}

# Ensure camera permissions and AUX whitelist (AOSP / custom ROMs)
{{AUX_WHITELIST_BLOCK}}

# Log
echo "[CameraPort] Service started for {{CODENAME}}" > /data/local/tmp/camera_port.log
